### ISSUE TITLE
Could you give some information about your cuda version?

### ISSUE THREAD

**Issue by ccJia** [wangruixing/DeepUPE#22]
Hi, I just  use makefile to compile your *.cc files but meet some compile problem.
![image](https://user-images.githubusercontent.com/7822492/61144033-638bbd80-a506-11e9-80f0-16a69fed1f0e.png)

 My cuda version is 10.0 . Do you meet problem like that?  Thanks.

**Comment by sangenan** [comment]
cuda8 work well，you can refer to the following links [](https://github.com/mgharbi/hdrnet_legacy/issues/24)

**Comment by sangenan** [comment]
https://github.com/mgharbi/hdrnet_legacy/issues/24

**Comment by ccJia** [comment]
@sangenan  Thank you, I will  flow this document. ^-^

**Comment by ccJia** [comment]
It based on cuda-8.0 and cudnn-5.1.

**Comment by vladpaunescu** [comment]
Hello! I can't use cuda-8.0, only cuda-10. Is there any fix for it?

**Comment by yuyifan1991** [comment]
@vladpaunescu I have the same issue, cuda-10 cannot make succesul?Have you solved the problem？
