### ISSUE TITLE
some problems about PSNR and dataset

### ISSUE THREAD

**Issue by JiaqianLi** [wangruixing/DeepUPE#24]
Hello, thank you for your work. 
I want to know whether the PSNR and SSIM results in table 2 in the original paper is tested on the RGB channel or Lab space as it is mentioned in HDRNet. In many previous works, they always use 4500 images for training, 250 images for validation and the randomly-chosen images for test on the MIT-Adobe Five5K dataset while in your model there are 500 images for test. I want to know if you use the same setting when re-train others' network.
Looking forward for your reply!

**Comment by wangruixing** [comment]
We have updated PSNR value in the errata. We use 4500 full-resolution images for training and 500 full-resolution images for testing, when we re-train other's network, we use the same setting.

**Comment by CV-JunchengLi** [comment]
这新结果和原论文结果也差距太大了吧，，，。
强烈谴责你们这种 行为！！！！

**Comment by JiaqianLi** [comment]
Hello, sorry to bother you. I want to know which 500 images are you used to test. Are they randomly selected or by order like 004500.jpg-004999.jpg? If they are randomly selected, could you please send me the list numer of the test images. Thank you very much!

**Comment by wangruixing** [comment]
> Hello, sorry to bother you. I want to know which 500 images are you used to test. Are they randomly selected or by order like 004500.jpg-004999.jpg? If they are randomly selected, could you please send me the list numer of the test images. Thank you very much!

We use 4501-5000 to evaluate our results.

**Comment by JiaqianLi** [comment]
Thank you for your reply. And I have another problem about the color loss. Could you please send the code of the color loss to my email 770534632@qq.com.

**Comment by wangruixing** [comment]
> Thank you for your reply. And I have another problem about the color loss. Could you please send the code of the color loss to my email [770534632@qq.com](mailto:770534632@qq.com).
Sure.

**Comment by JiaqianLi** [comment]
非常感谢，您的代码我收到啦！我最近想测试一下你GitHub上的代码，但是我那个make编译不了，会出现这样的错误：
nvcc fatal&nbsp; &nbsp;: Unknown option 'std'
make: *** [build/bilateral_slice.cu.o] Error 255

然后运行HDRNet也是同样的问题，所以想咨询一下，除了requirement.txt里面的包还需要什么环境。emmm要是可以的话能不能把重建好的结果放到github上，还有hdrnet_ops.so文件。或者发到我邮箱也可以。并不是想盗取你的研究成果，也没有其他目的，只是对比一下你的结果还有HDRNet的结果。。
祝好，
李佳倩


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wangruixing"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 下午3:19
收件人:&nbsp;"wangruixing/DeepUPE"<DeepUPE@noreply.github.com&gt;;
抄送:&nbsp;"爱之梦"<770534632@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangruixing/DeepUPE] some problems about PSNR and dataset (#24)



 
Thank you for your reply. And I have another problem about the color loss. Could you please send the code of the color loss to my email 770534632@qq.com.
 Sure.

**Comment by wangruixing** [comment]
> 非常感谢，您的代码我收到啦！我最近想测试一下你GitHub上的代码，但是我那个make编译不了，会出现这样的错误： nvcc fatal&nbsp; &nbsp;: Unknown option 'std' make: *** [build/bilateral_slice.cu.o] Error 255 然后运行HDRNet也是同样的问题，所以想咨询一下，除了requirement.txt里面的包还需要什么环境。emmm要是可以的话能不能把重建好的结果放到github上，还有hdrnet_ops.so文件。或者发到我邮箱也可以。并不是想盗取你的研究成果，也没有其他目的，只是对比一下你的结果还有HDRNet的结果。。 祝好， 李佳倩
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"wangruixing"<notifications@github.com&gt;; 发送时间:&nbsp;2019年10月21日(星期一) 下午3:19 收件人:&nbsp;"wangruixing/DeepUPE"<DeepUPE@noreply.github.com&gt;; 抄送:&nbsp;"爱之梦"<770534632@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [wangruixing/DeepUPE] some problems about PSNR and dataset (#24) Thank you for your reply. And I have another problem about the color loss. Could you please send the code of the color loss to my email 770534632@qq.com. Sure. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I will send it to you, however, I'm not sure it can be used in your environment since it should be compiled in your local environment.

**Comment by sangenan** [comment]
#22 Reading this will solve your compilation problems
