### ISSUE TITLE
The test result is not satisfactory.

### ISSUE THREAD

**Issue by jiangxuetao0823** [wangruixing/DeepUPE#26]
Hello, I appreciate your contribution. I used your pre-training model to test the FIVEK data set, and found that the output is darker than label, and the HDR effect is not obvious. Why is that? Can you release some test results? I want to compare them and verify what caused the problem.

**Comment by wangruixing** [comment]
When you use adobe5k lrcat to import the images, there are some different setting, I'm not sure my input setting is the same as yours, can you send me some your result by email, and I can give you some test results or can you check whether your input images is the same as my testing setting inputs?

**Comment by sangenan** [comment]
@wangruixing Hello, Thank you for your contribution. The input settings you use are "(default) input with ExpertC"?
![image](https://user-images.githubusercontent.com/8358472/61436862-4c1d5c00-a96e-11e9-99ae-b1b6e047c7aa.png)

**Comment by sangenan** [comment]
I used this setting and got nearly the same value as mentioned in the original paper.

**Comment by wangruixing** [comment]
@sangenan Yes.

**Comment by jiangxuetao0823** [comment]
@wangruixing  ok, my email is zjujxt@zju.edu.cn ,  I don't have your email, thanks

**Comment by jiangxuetao0823** [comment]
@sangenan Hello, what software do you use to import images and what format do you need to save the tested images? Thanks very much!

**Comment by jiangxuetao0823** [comment]
@sangenan can you give me your email, and I hope to learn and discuss with you, thanks.

**Comment by sangenan** [comment]
@jiangxuetao0823 
software：Adobe Lightroom
database: https://data.csail.mit.edu/graphics/fivek/ 
test format: jpg
label format: jpg

**Comment by jiangxuetao0823** [comment]
@sangenan The original data is in DNG format. Are you using lightROOM to convert DNG into jpg? Thanks a lot.

**Comment by sangenan** [comment]
@jiangxuetao0823  Yes, When you export picture, follow this setting
![image](https://user-images.githubusercontent.com/8358472/61443881-ebe1e680-a97c-11e9-8460-65c5ed445ff4.png)

**Comment by jiangxuetao0823** [comment]
@sangenan I know where the deviation is. I use the original DNG to do demasic and get the RGB image. Because the operation of Lightroom is unknown, I think Lightroom changes the distribution of image data, so I don't use it directly to convert the image. Finally, thank you very much for your help!

**Comment by ColdCodeCool** [comment]
> @jiangxuetao0823 Yes, When you export picture, follow this setting
> ![image](https://user-images.githubusercontent.com/8358472/61443881-ebe1e680-a97c-11e9-8460-65c5ed445ff4.png)

hi，I use adobe lightroom to convert dng to jpg，however， it automatically enhanced the dark part of the image. what is you setting for adobe lightroom

**Comment by ColdCodeCool** [comment]
@sangenan  hi，I use adobe lightroom to convert dng to jpg，however， it automatically enhanced the dark part of the image. what is you setting for adobe lightroom?
