### ISSUE TITLE
what is ''reflectance_files''  in the file 'data_pipeline.py'?

### ISSUE THREAD

**Issue by jiangxuetao0823** [wangruixing/DeepUPE#27]
'''
input_files = [os.path.join(dirname, 'input',f) for f in flist]
print(input_files[0])
output_files = [os.path.join(dirname, 'output', f) for f in flist]
reflectance_files = [os.path.join(dirname, 'reflectance', f) for f in flist]
'''
What is the reflectance_files，which is different from HDRnet. The training data only need input and label, I didn't understand what reflectance was here. Shouldn't it be an intermediate result? Does it need this reflectance for training?

I'm sorry I didn't understand. If it's convenient for you, could you help me? Thank you.

**Comment by wangruixing** [comment]
We don't use output_file during our training process, the reflectance is our gt file. the network's output is illumination map.

**Comment by jiangxuetao0823** [comment]
@wangruixing Thanks a lot.

**Comment by jiangxuetao0823** [comment]
with tf.name_scope('train'):
    with tf.variable_scope('inference'):
      illumination = mdl.inference(train_samples['lowres_input'], train_samples['image_input'], model_params, is_training=True)
      illumination_ = tf.cast(255.0*tf.squeeze(tf.clip_by_value(illumination, 0, 1)), tf.uint8)
      illumination_ = (tf.cast(illumination_, tf.float32)/255.0)**1
      illumination_ = tf.clip_by_value(illumination_, train_samples['image_input'], 1)
      prediction = np.divide(train_samples['image_input'], illumination_)

Hello, ruixing. There are some mistakes? My code work wrong all the time. Thanks a lot!
