### ISSUE TITLE
the network much like hdrnet 2017 ?

### ISSUE THREAD

**Issue by xuanzhangyang** [wangruixing/DeepUPE#3]
https://groups.csail.mit.edu/graphics/hdrnet/data/hdrnet.pdf

**Comment by wangruixing** [comment]
The main contribution of our paper is to propose a network for enhancing underexposed photos by estimating an image-to-illumination mapping, and design a new loss function based on various illumination constraints and priors.   Our network structure bilateral grid upsampling module design is inspired by HDNet.
Thanks.

**Comment by hangxiaotian** [comment]
数据集在哪里呢？

**Comment by Hbelief** [comment]
我暑假就看到chenjiawen那片文章了，看了你们的网络结构，第一反应是一股熟悉的气息！
