### ISSUE TITLE
ModuleNotFoundError: No module named 'main'

### ISSUE THREAD

**Issue by njustymk** [wangruixing/DeepUPE#34]
when i run it with :
CUDA_VISIBLE_DEVICES=2 python ./main/run.py checkpoints '/data2/xxx/data/data_DarkFace/image_train' '/data2/xxx/data/data_DarkFace/image_train_dupe_enhance'

i get 
Traceback (most recent call last):
  File "./main/run.py", line 15, in <module>
    import main.models as models
ModuleNotFoundError: No module named 'main'

**Comment by yuyifan1991** [comment]
@666xiaohei666 I have the same problem？Can you tell me how to solve it？
