### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so

### ISSUE THREAD

**Issue by njustymk** [wangruixing/DeepUPE#36]
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so

**Comment by wangruixing** [comment]
http://letmegooglethat.com/?q=Intel+MKL+FATAL+ERROR%3A+Cannot+load+libmkl_avx2.so+or+libmkl_def.so

**Comment by njustymk** [comment]
> http://letmegooglethat.com/?q=Intel+MKL+FATAL+ERROR%3A+Cannot+load+libmkl_avx2.so+or+libmkl_def.so

I followed the process, 
```
conda install nomkl numpy scipy scikit-learn numexpr
conda remove mkl mkl-service
```
but it didn't solve it.

**Comment by njustymk** [comment]
> http://letmegooglethat.com/?q=Intel+MKL+FATAL+ERROR%3A+Cannot+load+libmkl_avx2.so+or+libmkl_def.so

i install the requirement in a new docker and solve it ,thank you !
