### ISSUE TITLE
Image details loss?

### ISSUE THREAD

**Issue by jiangxuetao0823** [wangruixing/DeepUPE#38]
![499_test](https://user-images.githubusercontent.com/31535339/61710713-cc83f880-ad84-11e9-907b-25329bc787fd.jpg)
![499_label](https://user-images.githubusercontent.com/31535339/61710724-d1e14300-ad84-11e9-9bf4-0f1237d1b8e9.jpg)

**Comment by jiangxuetao0823** [comment]
Above is the output of the network during the training process, and below is the label. I don't know why the details are lost.

**Comment by rookie-jie-r** [comment]
where can find the training code?

**Comment by jiangxuetao0823** [comment]
@rookie-jie-r You can fininsh it according to run.py and hdrnet

**Comment by rookie-jie-r** [comment]
@jiangxuetao0823  Thank you ,but when I trained  ,the PSNR went to inf and nan .
Can you give me some suggestion.

**Comment by MohitLamba94** [comment]
@rookie-jie-r Can you please share the completed training code public so that I can also leverage it? Thankyou very much
