### ISSUE TITLE
Bilateral Grid Upsampling Layer 

### ISSUE THREAD

**Issue by ligua** [wangruixing/DeepUPE#4]
Hi, I am wondering whether I can ask something about the bilinear grid upsampling layer?

The original bilinear grid upsampling layer in the HDRNET seems to take a single-channel guide map and the feature map. Here it seems like it take the input image and the feature map(? not sure if I understand it right). Is it implemented in the manner as the HDRnet?

Also, I am wondering whether this bilateral grid upsampling layer actually help with the learning of the image to illumination mapping? Or it is just to apply the learned local affine transform to the high-res image?

Thank you so much and best regards

**Comment by wangruixing** [comment]
The bilateral grid upsampling layer is implemented in the manner as hdrnet, it helps to learn the image to illumination mapping to some extent, in addition, we use it to speed up our network.

**Comment by ligua** [comment]
So in your case, you abandon the guidance map, and directly apply the bilateral grid of the affine model upon the input image. Is this right?(I am not sure if I fully understand your approach)

**Comment by Chaway** [comment]
@ligua In this case, the input image can directly be seen as a guidance map in hdrnet?

**Comment by ligua** [comment]
@Chaway  Not sure, I did not really understand this part well. i probably need to read the source code of hdrnet more carefully. I am new to this

@wangruixing Sorry I forgot to reference. And I thank you so much for your help. Best Regards

**Comment by ligua** [comment]
@wangruixing Also, do you think that a standard network, let's say the generator of cyclegan, can learn the image-to-illumination mapping as well, if we apply the retinex-based model (basically decopose the image as reflectance and illlumination) and apply a smoothness loss, can this network still learn the mapping well?

I am sorry for all the misunderstanding, thank you so much and best regards
