### ISSUE TITLE
fatal error: third_party/eigen3/unsupported/Eigen/CXX11/Tensor: No such file or directory

### ISSUE THREAD

**Issue by yinyulin** [wangruixing/DeepUPE#43]
Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
ops/bilateral_slice.cu.cc:19:10: fatal error: third_party/eigen3/unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:31: recipe for target 'build/bilateral_slice.cu.o' failed
make: *** [build/bilateral_slice.cu.o] Error 1

**Comment by yinyulin** [comment]
when I use make to compile hdrnet_ops.so the error occur

**Comment by yuyifan1991** [comment]
@yinyulin I have the same issue，Can you tell me how to solve it？
