### ISSUE TITLE
error about "make failed"，How to deal with it

### ISSUE THREAD

**Issue by zyx1213271098** [wangruixing/DeepUPE#44]
![image](https://user-images.githubusercontent.com/35944726/62128701-8809d700-b307-11e9-8b34-b52a07cd2fd9.png)

**Comment by zyx1213271098** [comment]
I solved it. please check your tf version and cuda version.
it work with tf 1.1 with cuda 8.0!

**Comment by hermosayhl** [comment]
Would you tell me what had happened after you succeeded making them? I am having trouble making the makefile. Could you please share the result with me? 
Email( fluenceyhl@163.com ) and BaiduNetDisk is OK.
Best wishes!
