### ISSUE TITLE
Adobe5k dataset preprocessing 

### ISSUE THREAD

**Issue by sjmoran** [wangruixing/DeepUPE#49]
Hi, which Adobe5k images did you use in your training dataset? How did you preprocess the adobe5k images? Many thanks, Sean

**Comment by wangruixing** [comment]
https://github.com/wangruixing/DeepUPE/issues/26

**Comment by wangruixing** [comment]
https://github.com/wangruixing/DeepUPE/issues/26 You can follow the setting in this issue.
