### ISSUE TITLE
How to understand the formula of Smoothness Loss？

### ISSUE THREAD

**Issue by jiangxuetao0823** [wangruixing/DeepUPE#5]
Hello, I read your paper carefully, but I didn't understand the meaning of  smoothness loss formula. How does it guarantee local smoothness? Why do we do logarithmic operations on images? Could you explain it for me? Thank you very much.

**Comment by wangruixing** [comment]
Logarithmic operations make gradients more significant. Maybe you should read a paper "Interactive Local Adjustment of Tonal Values".

**Comment by jiangxuetao0823** [comment]
> Logarithmic operations make gradients more significant. Maybe you should read a paper "Interactive Local Adjustment of Tonal Values".

@wangruixing But, all pixel channels in Ix are normalized to [0,1], apply the logarithmic operations on it ,the gradients will reverse

**Comment by wangruixing** [comment]
Logarithmic operation only used by computing weight.

**Comment by jiangxuetao0823** [comment]
@wangruixing I know. In other words, if you want to make gradients more significant, you can multiply the gradients directly by a constant, and it is linear. However ,Logarithmic operations is non-linear, so what is the reason? Thanks a lot!

**Comment by wangruixing** [comment]
I have uploaded the smoothness loss implementation in metrics.py.
