### ISSUE TITLE
Make失败

### ISSUE THREAD

**Issue by KushinaYu** [wangruixing/DeepUPE#57]
Makefile:31: recipe for target 'build/bilateral_slice.cu.o' failed
make: *** [build/bilateral_slice.cu.o] Error 1

**Comment by KushinaYu** [comment]
cuda/include/cuda.h: No such file or directory

**Comment by wangruixing** [comment]
https://github.com/wangruixing/DeepUPE/issues/40 The issue may help you.

**Comment by yuyifan1991** [comment]
@KushinaYu Have you solve the problem？ I have the same trouble。
